### ISSUE TITLE
Fix the following line

### ISSUE THREAD

**Issue by light-weaver** [industrial-optimization-group/desdeo-tools#50]
```
        # TODO: Fix the following line
```

https://github.com/industrial-optimization-group/desdeo-tools/blob/04ce71f035c1e8f2b036086f15e1dfece4d4b87a/desdeo_tools/scalarization/ASF.py#L485

**Comment by light-weaver** [comment]
The phi value is not used anywhere? Is the implementation correct?

**Comment by bshavazipour** [comment]
Fixed. It was redundant.
